trigger:
- main

pool:
  name: Self_Agent_Pool

steps:
  - script: echo "Hello, World!"
    displayName: 'Run a one-line script'
  - script: |
      echo "This is a multi-line script."
      echo "You can run multiple commands here."
  - script: |
      echo "This is a script with a custom display name."
    displayName: 'Run a multi-line script with a custom name'