trigger:
- main

pool:
  name: Self_Agent_Pool

jobs:
- job: DryScript
  displayName: 'Run Multiple Scripts | Dry Run'
  steps:
    - script: echo "Hello, World!"
      displayName: 'Run a one-line script | Dry Run'
    - script: |
        echo "This is a multi-line script."
        echo "You can run multiple commands here."
      displayName: 'Run a multi-line script | Dry Run'
    - script: |
        echo "This is a script with a custom display name."
      displayName: 'Run a multi-line script with a custom name | Dry Run'
- job: TestScripts
  displayName: 'Run Multiple Scripts | Test'
  dependsOn: DryScript
  steps:
    - script: echo "Hello, World!"
      displayName: 'Run a one-line script | Test'
    - script: |
        echo "This is a multi-line script."
        echo "You can run multiple commands here."
      displayName: 'Run a multi-line script | Test'
    - script: |
        echo "This is a script with a custom display name."
      displayName: 'Run a multi-line script with a custom name | Test'
- job: ProdScripts
  displayName: 'Run Multiple Scripts | Prod'
  dependsOn: TestScripts
  steps:
    - script: echo "Hello, World!"
      displayName: 'Run a one-line script | Prod'
    - script: |
        echo "This is a multi-line script."
        echo "You can run multiple commands here."
      displayName: 'Run a multi-line script | Prod'
    - script: |
        echo "This is a script with a custom display name."
      displayName: 'Run a multi-line script with a custom name | Prod'